apiVersion: "nodemanager.aldunelabs.com/v1alpha2"
kind: "ManagedNode"
metadata:
  name: "cloudstack-dev-k3s-managed-01"
spec:
  nodegroup: cloudstack-dev-k3s
  controlPlane: false
  allowDeployment: true
  instanceType: small
  labels:
  - demo-label.acme.com=demo
  - sample-label.acme.com=sample
  annotations:
  - demo-annotation.acme.com=demo
  - sample-annotation.acme.com=sample
  network:
    cloudstack:
      - network: vpc-01
        dhcp: true
---
apiVersion: "nodemanager.aldunelabs.com/v1alpha2"
kind: "ManagedNode"
metadata:
  name: "cloudstack-dev-k3s-managed-02"
spec:
  nodegroup: cloudstack-dev-k3s
  controlPlane: false
  allowDeployment: true
  instanceType: small
  labels:
  - demo-label.acme.com=demo
  - sample-label.acme.com=sample
  annotations:
  - demo-annotation.acme.com=demo
  - sample-annotation.acme.com=sample
  network:
    cloudstack:
      - network: vpc-01
        dhcp: true
