//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 Frédéric Boltz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsManagedNodeNetwork) DeepCopyInto(out *AwsManagedNodeNetwork) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsManagedNodeNetwork.
func (in *AwsManagedNodeNetwork) DeepCopy() *AwsManagedNodeNetwork {
	if in == nil {
		return nil
	}
	out := new(AwsManagedNodeNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedNetworkConfig) DeepCopyInto(out *ManagedNetworkConfig) {
	*out = *in
	if in.OpenStack != nil {
		in, out := &in.OpenStack, &out.OpenStack
		*out = make([]OpenStackManagedNodeNetwork, len(*in))
		copy(*out, *in)
	}
	if in.VMWare != nil {
		in, out := &in.VMWare, &out.VMWare
		*out = make([]VMWareManagedNodeNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ENI != nil {
		in, out := &in.ENI, &out.ENI
		*out = new(AwsManagedNodeNetwork)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedNetworkConfig.
func (in *ManagedNetworkConfig) DeepCopy() *ManagedNetworkConfig {
	if in == nil {
		return nil
	}
	out := new(ManagedNetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedNode) DeepCopyInto(out *ManagedNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedNode.
func (in *ManagedNode) DeepCopy() *ManagedNode {
	if in == nil {
		return nil
	}
	out := new(ManagedNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedNodeList) DeepCopyInto(out *ManagedNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedNodeList.
func (in *ManagedNodeList) DeepCopy() *ManagedNodeList {
	if in == nil {
		return nil
	}
	out := new(ManagedNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedNodeSpec) DeepCopyInto(out *ManagedNodeSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Networking.DeepCopyInto(&out.Networking)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedNodeSpec.
func (in *ManagedNodeSpec) DeepCopy() *ManagedNodeSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedNodeStatus) DeepCopyInto(out *ManagedNodeStatus) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedNodeStatus.
func (in *ManagedNodeStatus) DeepCopy() *ManagedNodeStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRoutes) DeepCopyInto(out *NetworkRoutes) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRoutes.
func (in *NetworkRoutes) DeepCopy() *NetworkRoutes {
	if in == nil {
		return nil
	}
	out := new(NetworkRoutes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackManagedNodeNetwork) DeepCopyInto(out *OpenStackManagedNodeNetwork) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackManagedNodeNetwork.
func (in *OpenStackManagedNodeNetwork) DeepCopy() *OpenStackManagedNodeNetwork {
	if in == nil {
		return nil
	}
	out := new(OpenStackManagedNodeNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMWareManagedNodeNetwork) DeepCopyInto(out *VMWareManagedNodeNetwork) {
	*out = *in
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]NetworkRoutes, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMWareManagedNodeNetwork.
func (in *VMWareManagedNodeNetwork) DeepCopy() *VMWareManagedNodeNetwork {
	if in == nil {
		return nil
	}
	out := new(VMWareManagedNodeNetwork)
	in.DeepCopyInto(out)
	return out
}
