apiVersion: "nodemanager.aldunelabs.com/v1alpha2"
kind: "ManagedNode"
metadata:
  name: "openstack-dev-microk8s-master-02"
spec:
  nodegroup: openstack-dev-microk8s
  controlPlane: true
  allowDeployment: true
  instanceType: k8s.small
  diskSizeInMB: 10240
  labels:
  - demo-label.acme.com=demo
  - sample-label.acme.com=sample
  annotations:
  - demo-annotation.acme.com=demo
  - sample-annotation.acme.com=sample
  network:
    openstack:
      - network: "private"
        dhcp: false
        address: 192.168.32.11
        netmask: 255.255.255.0
---
apiVersion: "nodemanager.aldunelabs.com/v1alpha2"
kind: "ManagedNode"
metadata:
  name: "openstack-dev-microk8s-master-03"
spec:
  nodegroup: openstack-dev-microk8s
  controlPlane: true
  allowDeployment: true
  instanceType: k8s.small
  diskSizeInMB: 10240
  labels:
  - demo-label.acme.com=demo
  - sample-label.acme.com=sample
  annotations:
  - demo-annotation.acme.com=demo
  - sample-annotation.acme.com=sample
  network:
    openstack:
      - network: "private"
        dhcp: false
        address: 192.168.32.12
        netmask: 255.255.255.0
