apiVersion: "nodemanager.aldunelabs.com/v1alpha2"
kind: "ManagedNode"
metadata:
  name: "vsphere-dev-kubeadm-managed-01"
spec:
  nodegroup: vsphere-dev-kubeadm
  controlPlane: false
  allowDeployment: true
  instanceType: small
  diskSizeInMB: 10240
  labels:
  - demo-label.acme.com=demo
  - sample-label.acme.com=sample
  annotations:
  - demo-annotation.acme.com=demo
  - sample-annotation.acme.com=sample
  network:
    vmware:
      - network: "VLAN20"
        dhcp: true
      - network: "VM Network"
        dhcp: true
        use-dhcp-routes: false
---
apiVersion: "nodemanager.aldunelabs.com/v1alpha2"
kind: "ManagedNode"
metadata:
  name: "vsphere-dev-kubeadm-managed-02"
spec:
  nodegroup: vsphere-dev-kubeadm
  controlPlane: false
  allowDeployment: true
  instanceType: small
  diskSizeInMB: 10240
  labels:
  - demo-label.acme.com=demo
  - sample-label.acme.com=sample
  annotations:
  - demo-annotation.acme.com=demo
  - sample-annotation.acme.com=sample
  network:
    vmware:
      - network: "VLAN20"
        dhcp: true
      - network: "VM Network"
        dhcp: true
        use-dhcp-routes: false
